/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ACol: typeof import('@arco-design/web-vue')['Col']
    ARow: typeof import('@arco-design/web-vue')['Row']
    Banner: typeof import('./src/components/Banner.vue')['default']
    DraggableNext: typeof import('./src/components/draggableNext.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
